name: Snake Game

on:
  schedule:
    # Atualiza a cada 5 horas
    - cron: "0 */5 * * *"
  # Permite execução manual
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v2

      # Gera o SVG e GIF da cobrinha
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Jgonsan  # <-- altere para o seu nome de usuário no GitHub
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      #
